name: flutter_image_picker
description: Um widget de seleção de imagem
version: 0.0.1
homepage: https://github.com/LeonardoJRibeiro/flutter_image_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

